### ISSUE TITLE
Make flatMapErrors aware about service and endpoint context

### ISSUE THREAD

**Issue by msosnicki** [disneystreaming/smithy4s#1077]
Currently `flatMapErrors` is a `PartialFunction[Throwable, F[Throwable]]` that is the same for all the endpoints in the service.
In some cases, it would make sense to make this error handler aware about the service/endpoint context (similar to endpoint middlewares). To keep backwards compatibility, we could add an more generic method that allows for such fine grained handling, and leave `flatMapErrors` as is (with implementation delegating the the specialized version). 
Interested what are your thoughts about this

**Comment by kubukoz** [comment]
I think it's a good idea.

One realistic example of where this would be useful: logging only server errors (you need the schema of the errors, which you can get from the endpoint's `errorable`). Related to https://github.com/disneystreaming/smithy4s/issues/1070.

**Comment by Baccata** [comment]
This sounds like it could be solved via endpoint-specific middleware : https://disneystreaming.github.io/smithy4s/docs/guides/endpoint-middleware 

I don't think I'd be keen on adding another mechanism that'd be endpoint-specific. However, we could have short-hand constructors for endpoint-specific middlewares that'd have the purpose of dealing with errors.

**Comment by kubukoz** [comment]
What's the use in having the `flatMapErrors` / `mapError` utilities, then? Perhaps we can unify that with endpoint-specific middleware?

**Comment by Baccata** [comment]
Those are really an end-of-the-world, hail-mary catch-all mechanism that is conceptually simple enough for people to get productive.

Most of the time they will be used to customise the HttpContractErrors that are raised by smithy4s or to provide custom 500s.They're more about the errors that'd be defined at the level of the service in your smithy definition than anything. 

They've also been there a lot longer than endpoint-specific middleware, so I'm not keen to break them, though they could be reimplemented as endpoint specific middleware under the hood (which really, they are, despite not extending the interface)

**Comment by msosnicki** [comment]
I like the `flatMapErrors` mechanism and use it for mapping the application error hierarchy into the smithy4s error hierarchy that comes from codegen. 

The case I'm interested in, is being able to transform internal error ADTs into generated ones depending on which endpoint it is, so that same internal error will be treated differently depending on the context. I can do it with endpoint specific middlewares, but if I have another middleware I also want to apply, I'd need to compose then, and currently there is no build in way to compose them easily. 

Providing a `Semigroup` or other composition mechanism would help. 

It would also allow the use case @Baccata mentioned here: https://discord.com/channels/1045676621761347615/1073543230748102686/1118517020108013568

```
preErrorMiddleware |+| middleware |+| postErrorMiddleware
```

Currently, both `pre` and `post` are the same - `flatMapErrors`. Small doc section about such feature would be useful (or some helper builder methods for better UX), as this requires some knowledge about internals  to use it this way.

**Comment by Baccata** [comment]
> Providing a Semigroup or other composition mechanism would help.

Monoid instgances for enpoint-specific middlewares will be provided out-of-the-box in 0.18. In the meantime, it's easy enough to implement it in userland. Or to copy/paste. 

> Currently, both pre and post are the same - flatMapErrors
> Small doc section about such feature would be useful (or some helper builder methods for better UX), as this requires some knowledge about internals to use it this way.

If you want to PR something in so that `mapErrors/flatMapErrors` implementation is backed by endpoint-specific middlewares, that'd be great. 

What I'd be expecting from such a  PR would be : 

1. provide the following methods in the companion object of `ServerEndpointMiddleware` : 

```
def mapErrors[F[_]](f: Throwable => Throwable) :  ServerEndpointMiddleware[F]
def flatMapErrors[F[_]](f: Throwable => F[Throwable] : ServerEndpointMiddleware[F] 
```

2. provitde a `def andThen(other: ServerEndpointMiddleware[F]) : ServerEndpointMiddleware[F]` method in `ServerEndpointMiddleware` interface (same for `ClientEndpointMiddleware`), and change the implementation of the monoid to delegate to that method. Having an actual method helps UX. 
3. Change the implementation of the existing `mapErrors/flatMapErrors` methods to delegate to the `ServerEndpointMiddleware` static methods, and compose them left and right with the existing middleware in  `RouterBuilder`
4. Remove the `errorTransformation` constructor parameter in `RouterBuilder` (which shouldn't have a reason to leave anymore) 
5. Improve the documentation of the endpoint-specific middleware with the new details, and the documentation of `mapErrors/flatMapErrors` with the fact that it's just a shorthand for : 

``` 
errorTransformation |+| middleware |+| errorTransformation
```

I don't think I'd want to have more methods on `RouterBuilder` to configure pre/post error transformations individually. The desire to want to keep the existing `mapErrors` / `flatMapErrors` methods stems from not wanting to break end-users. However, if more granular error transformations are to be applied, they should be encoded as middlewares .

**Comment by msosnicki** [comment]
Sounds good, I was thinking about something similar. Happy to work on it. 
Just few followup questions:

1. Any reason why `Monoid` is not backported to `0.17`? I could add them as well as part of the PR (and delagate to the `andThen` methods you mentioned). 

2. 
> 4. Remove the errorTransformation constructor parameter in RouterBuilder (which shouldn't have a reason to leave anymore)

I think it needs to stay there, as it is need to be part of the builder, until the `build` happens (only then we compose `pre |+| mid |+| post`).

Edit: actually, you mention in 3 that it should compose with the existing middleware. Isn't that error prone to the user? The builder behavior would depend on the order you invoke `middleware` & `mapErrors`. I guess if it's clearly documented to first set middleware and then use `flatMapErrors/mapErrors`, it should be fine for new users, but it could still break current usage if the order is different.

**Comment by Baccata** [comment]
> Any reason why Monoid is not backported to 0.17? 

Lack of resources, mostly. We're not promising any kind of LTS on 0.17, but I'm happy for you to backport this if you'd like. 

> Edit: actually, you mention in 3 that it should compose with the existing middleware. Isn't that error prone to the user

Hah, good point. Let's keep the constructor parameter (the constructor should be private anyway) and only compose left and right upon `build.`
