### ISSUE TITLE
minimal examples of publishing smithy4s artefacts as a library

### ISSUE THREAD

**Issue by ShahOdin** [disneystreaming/smithy4s#1479]
I want to be able to:

- have a multi modules sbt project where there is a smithy module and another one that depends on the said module. (as opposed to the example provided in the docs that has both in one module)
- use the published library remotely, as opposed to locally as described above.

Another seperate use case I'd like to think about, is the possibility of implementing and hosting different versions of a smithyservice. say v1 and v2. Can the existing tooling make this happen without me having to have these in different namespaces? cos if the two specs are in different namespaces, they are no longer:

- `service Foo { version: "v1" }`
- `service Foo { version: "v2" }`

they are instead effectively:

- `service FooV1 { version: "v1" }`
- `service FooV2 { version: "v1" }`

**Comment by Baccata** [comment]
Regarding publishing/consuming artifacts containing smithy4s-produced code, it should just work without you having to configure anything specific, whether in a multi-module setting or not. This is described here : https://disneystreaming.github.io/smithy4s/docs/overview/sharing-specs#smithy4s-context

If it doesn't work, please open another issue with a repro of what you've tried. 

Regarding versions: no, smithy4s doesn't make any use of the version number of services, and we're not planning to do anything specific with it either. You may want to ask the smithy maintainers about them https://github.com/smithy-lang/smithy

Closing because this should have been open as a GitHub discussion (or a question on the discord channel) rather than an issue.
