### ISSUE TITLE
Add a default implementation for `getMessage` in `Smithy4sThrowable` 

### ISSUE THREAD

**Issue by Baccata** [disneystreaming/smithy4s#1497]
Some users are getting confused because of libraries that print `getMessage`, which currently returns `null` for smithy4s-generated throwables, except if one of the fields is identified to be a message field.

**Comment by daddykotex** [comment]
The [PR that introduced this](https://github.com/disneystreaming/smithy4s/commit/2f51c44f5adf864d96e0d04814149fdeec8061c1). I guess we can do something smart. The reason I implemented `toString` instead of `getMessage` was that the default `toString` calls `getMessage` and so if the former is not overridden, the output error message was awkward.

Maybe implementing both would work as expected.

**Comment by Baccata** [comment]
> Maybe implementing both would work as expected. 

That is indeed what I think we should do.
