### ISSUE TITLE
Blob equals issue

### ISSUE THREAD

**Issue by msosnicki** [disneystreaming/smithy4s#1521]
Currently `Blob` has three variants, two of which define `equals` in the following way:

```scala
    override def equals(other: Any): Boolean = {
      other.isInstanceOf[ByteBufferBlob] &&
      buf.compareTo(other.asInstanceOf[ByteBufferBlob].buf) == 0
    }
``` 
meaning that `ArraySliceBlob` will never be equal to `ByteBufferBlob`.

In addition to that, `QueueBlob` does not define `equals` and `hashCode` at all.

**Comment by Baccata** [comment]
The absence of `equals` and `hashCode` in QueueBlob is indeed a bug. 

However, the fact that `equals` takes into consideration the underlying structure is by design. If you're looking to compare the bytes of two blobs, you should use [sameBytesAs](https://github.com/disneystreaming/smithy4s/blob/7cc1aa9a1b34d30b90308eedd1edb7a7ddd7e1aa/modules/core/src/smithy4s/Blob.scala#L58-L68)

**Comment by msosnicki** [comment]
Do you have an example of scenario where it is useful to know the exact underlying type of a `Blob` and take it into consideration when using `equals`? Noticed that the types themselves are not hidden as well, so it's visible now that it didn't happen by accident. Thanks

**Comment by Baccata** [comment]
I suppose we could implement the equals method using sameBytesAs, it would be less of a surprising behaviour for users. Comparisons that need to be structure aware can inspect the structure. 

PR away, if you want

**Comment by msosnicki** [comment]
Ok, will raise one today
