### ISSUE TITLE
Sharing smithy files in a multi-project build

### ISSUE THREAD

**Issue by danielkarch** [disneystreaming/smithy4s#391]
Hi, 

I have a project with two submodules, `moduleA` and `moduleB`. Both use smithy4s and have their smithy files in their respective `src/main/smithy` directory. Now with the introduction of refinements, I would like to create a new module, `refinements`, such that both `moduleA` and `moduleB` depend on `refinements`. 
Unfortunately I cannot get this to work. I defined the `smithy4sInputDir` in the `smithyRefinements` module as
```
Compile / smithy4sInputDir := baseDirectory.value / "src/main/resources/META-INF/smithy"
```
and defined a file `refinements.smithy`
```
namespace refinements

structure Foo {}
```
as well as a `manifest` referring to that file. The `smithyRefinements / smithy4sCodegen` task runs fine and generates `Foo.scala`, i.e., smithy4s finds the `refinements.smithy` file.

In the `build.sbt` I let `moduleA` depend on `smithyRefinements`:
```scala
lazy val smithyRefinements = ...
lazy val moduleA = (project in file("modules/moduleA"))
  .dependsOn(smithyRefinements)
  ...
  .enablePlugins(Smithy4sCodegenPlugin)
```
In `modules/moduleA/src/main/smithy/ModuleA.smithy` I depend on `refinements#Foo`:
```
namespace moduleA

use refinements#Foo

structure Blah {
    foo: Foo
}
```
but when I run `moduleA / smithy4sCodegen`, I get the error
```
[error] (moduleA / Compile / smithy4sCodegen) software.amazon.smithy.model.validation.ValidatedResultException: Result contained ERROR severity validation events: 
[error] [ERROR] moduleA#Blah$foo: member shape targets an unresolved shape `refinements#Foo` | Target /.../modules/moduleA/src/main/smithy/ModuleA.smithy:8:5
```

What am I missing? I was able to depend on smithy files defined in another library, as described [here](https://github.com/disneystreaming/smithy4s/blob/main/modules/docs/src/01-overview/05-sharing-specs.md), but not when they are defined in another module in the same project.

**Comment by daddykotex** [comment]
This is tricky. What you're essentially trying to is to share the code generation output from one project (refinements) into another project ( A and/or B). This works, but you get blocked before because the code generation process from the module A & B can't import the smithy model. When you define a dependency on the refinement model, it does not tell smithy4s that there are `smithy` file in there what would need to be added to the model to resolve it.

I think there are more than one ways to solve this issue. None of them are _clean_ in my opinion but you may find something that suits your need. I'll create an example project to experiment and share with you how I would do it.

I'll circle back in a bit.

**Comment by kubukoz** [comment]
I've hit this in the past and I think we should consider supporting this usecase natively.

People might want to generate code for their models in one module, and services (using these models) in another module, for example.

**Comment by daddykotex** [comment]
Unfortunately, while looking at this, I realized that's it's not supported right now. But as @kubukoz , it would be great if it was so we'll definitely look into it. In the meantime, I've created an example of a multi module layout that you could use to do what you want. Unfortunately, this does not do what you want: have smithy specs in different location. But I think the end result is the same. It's here: https://github.com/daddykotex/smithy4s-multi-module

We'll keep this issue open as it would be nice to have.

On the other hand, I'm quite surprised that the `discoverModels = true` does not fine the `refinements.smithy` on the class path because:

1. there is a module dependency
2. it is located in the `resources` of said modules

And so it should be on the classpath for module A and module B

**Comment by danielkarch** [comment]
Thanks for looking into this. I would be happy to help with this, but I don't yet know where to start.

**Comment by yisraelU** [comment]
@danielkarch I'm curious if you generate a manifest file for the smithy files in Module A and place it in the META-INF/smithy folder , if it will work

**Comment by danielkarch** [comment]
@yisraelU no, that did not make any difference.

**Comment by Baccata** [comment]
@danielkarch thanks for reporting. I'm trying to formulate a plan to make UX reasonably nice and intuitive for this usecase (I'm currently on holiday so I'm likely to not reply in a timely fashion).   

1. We need for smithy4s to package models as resources for downstream modules to consume. In SBT, this implies an additional resource generator. This would be enabled by default, and could be disabled via a setting. 
2. We need for smithy4s to create metadata for the code that it's generated, that would also be packaged. Could use smithy "metadata" for this. This would allow for downstreams to skip the generation for namespaces that were previously generated. 
3. We need to wire things such that the user can say `.dependsOn(foo % "compile -> compile, smithy4s -> compile")` to communicate that a project downstream of `foo` that it should use foo's smithy models in the validation of its own models. I'm not quite sure whether that should be default actually. 

Anyhow, there's a lot of nuance to take into consideration, I'll try to do a more fully-fledged write up next week.

**Comment by Baccata** [comment]
@danielkarch the latest release (0.16.1) should make your usecase work, without having to change the `smithy4sInputDir `. 

Head over [there](https://disneystreaming.github.io/smithy4s/docs/overview/sharing-specs#smithy4s-context) from some documentation, and over [there](https://github.com/disneystreaming/smithy4s/tree/main/modules/codegen-plugin/src/sbt-test/codegen-plugin/multimodule) to see a test that shows that it works. You'll see in the `build.sbt` of that test that you don't have to do anything.

**Comment by danielkarch** [comment]
Thank you!
