### ISSUE TITLE
Generated client does not map HTTP error to custom type

### ISSUE THREAD

**Issue by danielkarch** [disneystreaming/smithy4s#413]
Hi, 

I have defined a custom error type and an operation that returns that error
```
namespace acme.api

use smithy4s.api#simpleRestJson

@simpleRestJson
service HelloWorldService {
  version: "1.0.0",
  operations: [Boom]  
}

@http(method: "POST", uri: "/boom", code: 200)
operation Boom {
  input: Unit,
  output: Unit,
  errors: [MyError]
}

@error("client")
structure MyError {
}
```
Note that I did not specify _which_ client error should be mapped here (i.e., there is no `@httpError` annotation). Further I have generated a client for the `HelloWorldService`: 
```scala
HelloWorldService.simpleRestJson.clientResource(
    httpClient,
    Uri.unsafeFromString("http://google.com/giveme404")
)
```
As you can see, the client will call a URL that returns a 404. According to [the smithy documentation](https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html)

> The httpError trait is used to set a custom HTTP response status code. By default, error structures with no httpError trait use the default HTTP status code of the [error trait](https://awslabs.github.io/smithy/1.0/spec/core/type-refinement-traits.html#error-trait).
>
> -  400 is used for "client" errors
> -  500 is used for "server" errors

Hence I would expect that smithy4s would map all client errors to `MyError`. This is the case with `v0.14.2`, but not with `v0.15.1`. Now it will instead raise an `UnknownErrorResponse` error. I can provide a repository with a small example if necessary.

I believe I found the [piece of code](https://github.com/disneystreaming/smithy4s/blob/c9839dbdf2b7f81478e233beae0853ad499a0c2a/modules/core/src/smithy4s/http/ErrorAltPicker.scala#L44) that is responsible for this behaviour, but before I try to "fix" it I would like to know whether this is indeed a bug. I found the [commit](https://github.com/disneystreaming/smithy4s/commit/092b4beadd1141cc1a0db89088ebd7187dc78adc) where this was changed and am not sure if maybe it is now behaving as intended.

**Comment by danielkarch** [comment]
Okay, I see that the previous behaviour would be problematic if there would be multiple structures like `MyError` without `@httpError` defined. Smithy4s would have no way of knowing which one it should pick.

**Comment by kubukoz** [comment]
is this just https://github.com/disneystreaming/smithy4s/pull/357 ? I don't have a lot of context but it seems like an intentional change. It's documented in the release notes as a "fix" but should probably have been described as possibly breaking semantically.

**Comment by danielkarch** [comment]
Yes, this it probably intentional. You can close it. I just wonder, do I now have to create a dedicated error structure for each client error?

**Comment by Baccata** [comment]
@danielkarch, Smithy4s will try to discriminate according to the following rules : 

1. If a `X-Error-Type` header is found, with a value being the name of an error type Smithy4s knows is tied to the operation, it'll try to decode to that. Obviously that works mostly for services that are implemented using Smithy4s. 
2. Otherwise, if all errors tied to an operation are uniquely mapped to status codes, it'll try to use that. 

As you've noticed, the previous behaviour was problematic and leading to an overly eager error selection. There's now no built-in mechanism for "catch-all errors", the best course of action is to : 

1. Create a dedicated error structure for each status code you can predict. Thankfully, with Smithy 2.0 and the apparition of mixins, the boilerplate can be greatly reduced. 
2. Recover from `UnknownErrorResponse`

I'm not quite sure whether errors that have the`@error("client")` trait but no `httpError` trait should be turned into "catch-all errors" again, implying that on the client-side, expecting 400/500 should not necessarily be a thing. It may actually be acceptable, but I'll need to give it a think.

**Comment by danielkarch** [comment]
Thanks, I will take a look at mixins. :+1: 

BTW, this reminded me of [this xkcd](https://xkcd.com/1172/). :smile:

**Comment by daddykotex** [comment]
Do we want to take further action on this @Baccata ?

**Comment by Baccata** [comment]
@daddykotex yeah I think so. IE, [these lines](https://github.com/disneystreaming/smithy4s/blob/main/modules/core/src/smithy4s/http/ErrorAltPicker.scala#L51-L52) should be replaced, so that `byStatusCode` value should actually become a `Int => Option[SchemaAlt[E, _]]` instead of Map. 

The behaviour should be that if the status code doesn't map precisely to an error annotated with `@httpCode`, but exactly one error happens to have `@error("client")` without `@httpCode`, that error should be selected (provided the status code is in the 4xx range ). Same for `@error("server")` and 5xx range.
