### ISSUE TITLE
Support `cors`

### ISSUE THREAD

**Issue by daddykotex** [disneystreaming/smithy4s#449]
Some users have requested the ability to generate the code to support CORS. This trait currently is not taken in consideration by the `simpleRestJson` protocol.

https://awslabs.github.io/smithy/2.0/spec/http-bindings.html?highlight=cords#cors-trait

**Comment by kubukoz** [comment]
One thing that bothers me about the trait is that there's just one `origin`. A string, not a list. It feels very limiting to only support one origin, as normally you might want to include e.g. your development setup (localhost).

**Comment by kubukoz** [comment]
For example, http4s supports a list of allowed origins:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/894884/189465911-f968dfd3-33aa-4a91-b827-ed9c7cb07b69.png">

so that when you make a request from one of them, it'll be returned in the allowed origin header. I believe that's a pretty common pattern even outside of http4s.

**Comment by Baccata** [comment]
>  Some users have requested the ability to generate the code to support CORS. This trait currently is not taken in consideration by the simpleRestJson protocol.

This is one of the things I'm really not willing to provide OOTB support for, because it can be supported by http4s-level middleware easily in third-party code/userland. See [the http4s docs](https://http4s.org/v1/docs/cors.html). 

Moreover, as @kubukoz states, the cors trait ain't as flexible as it should, so providing OOTB support would be lacking. 

What we can do however is document how to retrieve hints from services (both in a polymorphic and monomorphic manner), and document an example of doing that for wiring a CORS middleware.

**Comment by Baccata** [comment]
Issued open upstream : https://github.com/awslabs/smithy/issues/1396

**Comment by daddykotex** [comment]
Opened https://github.com/disneystreaming/smithy4s/pull/456 to document how to implement such a thing on your own until the issue is fixed upstream

**Comment by Baccata** [comment]
Gonna close this, the documentation on how to enable CORS is enough.
