### ISSUE TITLE
Ordering for generated enum

### ISSUE THREAD

**Issue by ahjohannessen** [disneystreaming/smithy4s#533]
I would be nice if Ordering instance was provided for generated enum in its companion, e.g.:

```scala
object CodegenEnum extends Enumeration[CodegenEnum] with ShapeTag.Companion[CodegenEnum] {
  ...
  implicit val ordering: Ordering[CodegenEnum] = Ordering.by[CodegenEnum, Int](_.intValue)
  ...
}
```

**Comment by Baccata** [comment]
I don't think it should be added, because who are we to decide whether an enumeration should be better sorted by its integer value, or string value, or at all, for that matter ? 

There is argueably nothing inherent to the concept of "enumeration" that is order-able. It is heavily contextual and not the place of the library to make a decision. 

Moreover, if it's something you find yourself needing often, you could easily define one in userland : 

```
implicit def enumOrdering[E <: smithy4s.Enumeration.Value] : Ordering[E] = Ordering.by[E, Int](_.intValue)
```

**Comment by ahjohannessen** [comment]
Good point :) Yeah, needed it for `NonEmpySet` - but your suggestion is nice 👍
