### ISSUE TITLE
Setting content-type on inputHasBody=false

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#71]
In the http4s client interpreter, we have this logic:

```scala
if (inputHasBody) {
  baseRequest.withEntity(input)
} else baseRequest
```

Because of it, there's no way (AFAIK) to set a content-type for endpoints that don't take anything in the body, which is the case e.g. in [Sonos's seek API](https://developer.sonos.com/reference/control-api/playback/seek/). What would be the idiomatic way to approach this here?

My workaround is probably going to be setting a default content-type for all requests to this host.

This relates to #28, I assume.

**Comment by Baccata** [comment]
I mean, if there's no content, why would there be a need for a content type ?

What's the behaviour of the API you're trying to hit ?

**Comment by kubukoz** [comment]
It fails when there's none 😂

**Comment by Baccata** [comment]
That's what I thought 😅 

I don't think I want to support a solution to that particular problem : it is downright impossible for every single Http API to be described in smithy, and trying to do so would only lead to customisation-creep and despair. The value of smithy (and therefore smithy4s), as I see it, is that you gain a lot of toolability if you accept to constrain your API to a specific "protocol" and to what smithy allows for. You cannot get the same toolability from openapi, because it's just too permissive and tries to make it possible for every http API ever made to be described in its semantics, and I don't think this is a goal worth pursuing. 

It's a "liberty constrains, constraints liberate" kind of thing. 

I'm willing to compromise _a little_ here and there, by incorporating things such as discriminated/untagged unions in the protocols I support, but that's about it really. I don't want to invent semantics out of thin air to be able to support niche caveats of random public APIs. In particular when these caveats can be easily addressed/worked-around via http4s middleware. 

So, to me, your workaround idea is the correct approach 👍 . In other words, a `Client[F] => Client[F]` that'd automatically set a `Content-Type` header in the requests before dispatch if there is none present.

**Comment by kubukoz** [comment]
Fair enough :)
