### ISSUE TITLE
`smithy4s.codegen.BuildInfo.smithyVersion` contains a different version than the plugin

### ISSUE THREAD

**Issue by lolgab** [disneystreaming/smithy4s#807]
When I import the smithy4s mill plugin:
```
import $ivy.`com.disneystreaming.smithy4s::smithy4s-mill-codegen-plugin::0.17.3`
```

`smithy4s.codegen.BuildInfo.smithyVersion` contains `0.17.2`.

It seems that the version is [derived](https://github.com/disneystreaming/smithy4s/blob/series/0.17/build.sbt#L385) from a static version you have in Dependencies.scala and not from the current tag.

**Comment by Baccata** [comment]
That's because you're looking at the wrong value. What you want is `smithy4s.codegen.BuildInfo.version`, which gives you the version of smithy4s. 

The `smithyVersion` value corresponds to the version of the [smithy](https://github.com/awslabs/smithy) libraries from AWS, which smithy4s.codegen uses to implement the code-generation logic. 

That being said, I find it very weird that `smithy4s.codegen.BuildInfo.smithyVersion` would contain `0.17.2`. I tried it out and it contained `1.27.2` as [expected](https://github.com/awslabs/smithy/releases/tag/1.27.2). 

I guess it's confusing because Scala people use `smithy` and `smithy4s` interchangeably 😅

**Comment by lolgab** [comment]
Yes! I definitely got confused.
Thank you for the explanation!
