### ISSUE TITLE
[ComplianceTest] PathEncode fails on Byte

### ISSUE THREAD

**Issue by yisraelU** [disneystreaming/smithy4s#815]
The following protocol test https://github.com/awslabs/smithy/blob/main/smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-byte.smithy 
has triggered the following failure
https://github.com/disneystreaming/smithy4s/actions/runs/4186363106/jobs/7254760090
This was a bit of a rabbit hole discovering this

**Comment by Baccata** [comment]
It's not really pre-emptive caching that causes the exception, but yeah I don't think it qualifies as a bug really. 

The bug is more that it looks like validation is not run after applying the model transformer and before running the code generation, because we have a validator in place that ensures that all operations of a service annotated with `simpleRestJson` are bound to http semantics.

**Comment by yisraelU** [comment]
IMO this is definitely not a bug , more of a gotcha situation (I thought that part was clear)
I am not saying its the caching that causes the error , it is an invalid http endpoint error, however the Malformed operation would never have been passed to ```SmithyHttp4sClientEndpoint.make()```  as its Test is filtered out in the stream filter.
the only reason why ```SmithyHttp4sClientEndpoint.make()``` is called evaluated for the malformed endpoint is because the caching is done preemptively

**Comment by Baccata** [comment]
My point is that `MalformedByte` operation should not even have passed validation/ been dumped into the json model in the first place, because the absence of h`@http` on it violates a build-time invariant. 

Also, please add the source of the test to the description of the issue. Github issues are not private conversations, their description should contain enough information for people with less context to be able to follow along.

**Comment by yisraelU** [comment]
Ok let me clarify
> My point is that `MalformedByte` operation should not even have passed validation/ been dumped into the json model in the first place, because the absence of h`@http` on it violates a build-time invariant.
> 
 that's not correct,
```MalformedByte``` as well as all the Malformed Operations  **have** the ```@http``` trait on it.

>The bug is more that it looks like validation is not run after applying the model transformer and before running the code generation, because we have a validator in place that ensures that all operations of a service annotated with simpleRestJson are bound to http semantics.
> 
Validation would have succeeded per ☝️ , however I do think we do not validate post transformations  and we should https://github.com/disneystreaming/smithy4s/blob/37386abe5bfd9de412f2675dc6c60086696b2f6c/modules/codegen/src/smithy4s/codegen/internals/ModelLoader.scala#L100

As far as the root of the Exception, I stand corrected ,it is **indeed** a bug in the SchemaVisitorPathEncoder that veers  from the [spec](https://smithy.io/2.0/spec/http-bindings.html#httplabel-trait) ,This is because we don't define  a PathEncode for Byte https://github.com/disneystreaming/smithy4s/blob/37386abe5bfd9de412f2675dc6c60086696b2f6c/modules/core/src/smithy4s/http/internals/SchemaVisitorPathEncoder.scala#L51
https://github.com/disneystreaming/smithy4s/blob/37386abe5bfd9de412f2675dc6c60086696b2f6c/modules/core/src/smithy4s/http/internals/SchemaVisitorPathEncoder.scala#L33

1. I think the  ```HttpEndpointError``` should not have been reduced to the generalized message 
It would be valuable to retain  the source of the problem 
https://github.com/disneystreaming/smithy4s/blob/37386abe5bfd9de412f2675dc6c60086696b2f6c/modules/http4s/src/smithy4s/http4s/SmithyHttp4sReverseRouter.scala#L65
2. We should add Byte to the SchemaVisitorPathEncoder

I can open a PR for both of these if you approve

**Comment by Baccata** [comment]
👍 thanks for the clarifications, I was indeed in the wrong. Happy for you to open PRs for both these things

**Comment by yisraelU** [comment]
solved by #819
